export const proyectos = [
    {
        id: 0,
        img: "images/proyectos/flecha.png",
        title: "Bienvenido a mi Portfolio",
        description: `<div class="flecha-p" > <p>Desliza hacia abajo para ver los proyectos</p><br><img src="images/flecha.png" alt="Flecha" /><div/> `,
        className: "welcome-slide",
    },
    {

        id: 1,
        img: "images/proyectos/contra.png",
        title: "Contra - Architecture",
        description: "App web del grupo de Arquitectura Español con integración de elementos multimedia y sistemas dinámicos basado en JavaScript. Operaciones CRUD integradas en Google Sheets.",
        bandera: "images/proyectos/banderas/esp.png",
        link: "https://www.contra-architecture.com/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/react.png",
        skill4name: "React",
        skill5: "images/languages/js-white.png",
        skill5name: "Js",
        skill5: "images/languages/api-white.png",
        skill5name: "API",
        video: "images/proyectos/contra.mp4",
        videoCel: "images/proyectos/contra-cel.mp4",
        fecha: "2023-10-30",
        destacado: true,
    },
    {
        id: 2,
        img: "images/proyectos/baires.png",
        title: "Baires Flights",
        description: "Sitio web diseñado y desarrollado en React-JS facilita el envío de formularios específicos de pasajeros, y optimizando la interacción con llamados a la acción. Posee además traducción ESP-ING.",
        bandera: "images/proyectos/banderas/arg.png",
        link: "https://bairesflights.com.ar/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/react.png",
        skill4name: "React",
        video: "images/proyectos/baires.mp4",
        fecha: "2024-04-22",
        destacado: true
    },
    {
        id: 3,
        img: "images/proyectos/decoinox.png",
        title: "Decoinox",
        description: "Sitio web diseñado en Figma y desarrollado en React-JS para Decoinox, destacando su catálogo de productos y optimizando la conversión mediante llamados a la acción.",
        bandera: "images/proyectos/banderas/arg.png",
        link: "https://decoinox.com.ar/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/react.png",
        skill4name: "React",
        video: "images/proyectos/decoinox.mp4",
        fecha: "2024-08-16",
        destacado: true
    },
    {
        id: 4,
        img: "images/proyectos/artanium.png",
        title: "Artanium",
        description: "Creado con un enfoque en la experiencia del usuario y desarrollado en React-JS. Muestra de manera clara los productos de la empresa e incluye una funcionalidad de búsqueda para facilitar la navegación.",
        bandera: "images/proyectos/banderas/arg.png",
        link: "https://www.artanium.com.ar/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/react.png",
        skill4name: "React",
        video: "images/proyectos/artanium.mp4",
        fecha: "2023-08-30",
        destacado: false
    },
    {
        id: 5,
        img: "images/proyectos/senko.png",
        title: "Senko",
        description: "Sitio web desarrollado en WordPress que presenta un catálogo de productos y permite solicitar cotizaciones a través de correo electrónico. Es autoadministrable, lo que facilita la gestión de contenido por parte del usuario.",
        bandera: "images/proyectos/banderas/arg.png",
        link: "https://senko.com.ar/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/react.png",
        skill4name: "React",
        video: "images/proyectos/senko.mp4",
        fecha: "2024-08-05",
        destacado: false
    },
    {
        id: 6,
        img: "images/proyectos/lusqtoff.png",
        title: "Lusqtoff Tigre",
        description: "E-commerce diseñado en Tienda Nube para la reconocida marca Lusqtoff, con CSS personalizado que refleja su identidad de marca y mejora la experiencia del usuario.",
        bandera: "images/proyectos/banderas/arg.png",
        link: "https://lusqtofftigre.com.ar/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        video: "images/proyectos/lusqtoff.mp4",
        fecha: "2024-09-20",
        destacado: true
    },
    {
        id: 7,
        img: "images/proyectos/versa.png",
        title: "Versa Digital",
        bandera: "images/proyectos/banderas/arg.png",
        description: "Desarrollo del sitio web de la agencia digital. Condicional js para el renderizados de diversas recomendaciones por rubro.",
        link: "https://versadigital.com.ar",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/js-white.png",
        skill4name: "Js",
        skill5: "images/languages/react.png",
        skill5name: "React",
        video: "images/proyectos/versa.mp4",
        fecha: "2023-04-08",
        destacado: false
    },
    {
        id: 8,
        img: "images/proyectos/hoop.png",
        title: "HOOP Perú",
        bandera: "images/proyectos/banderas/per.png",
        description: "Sitio web de la ONG, que presenta información sobre la organización. Se destaca su navbar personalizado con imágenes que mejora la navegación, fue desarrollado en colaboración con diseñadores UX/UI y developers.",
        link: "https://www.hoopperu.org/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/git.png",
        skill3name: "Git",
        skill4: "images/languages/js-white.png",
        skill4name: "Js",
        skill5: "images/languages/react.png",
        skill5name: "React",
        video: "images/proyectos/hoop.mp4",
        fecha: "2023-06-09",
        destacado: true
    },
    {
        id: 9,
        img: "images/proyectos/rimmaudo.png",
        title: "Dr. Rimmaudo",
        bandera: "images/proyectos/banderas/arg.png",
        description: "Desarrollo del sitio web profesional en React.js, que incluye un mapa interactivo de los consultorios y una lista detallada de servicios ofrecidos",
        link: "https://www.drdiegobrimmaudo.com.ar/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/react.png",
        skill4name: "React",
        video: "images/proyectos/rimmaudo.mp4",
        fecha: "2023-08-14",
        destacado: false
    },
    {
        id: 10,
        img: "images/proyectos/biondi.png",
        title: "Estudio Biondi",
        bandera: "images/proyectos/banderas/arg.png",
        description: "Creación del sitio web del profesional. Diseño personalizado.",
        link: "https://estudiobiondi.com/",
        skill1: "images/languages/html-white.png",
        skill1name: "HTML5",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        skill3: "images/languages/sass.png",
        skill3name: "Sass",
        skill4: "images/languages/react.png",
        skill4name: "React",
        video: "images/proyectos/biondi.mp4",
        fecha: "2023-05-03",
        destacado: false
    },
    {
        id: 11,
        img: "images/proyectos/tobyco.png",
        title: "Tobyco Constructora",
        description: "Landing page de la constructora, desarrollado en WordPress, que presenta de manera clara todos los tipos de construcción y servicios disponibles",
        bandera: "images/proyectos/banderas/arg.png",
        skill1: "images/languages/wordpress-white.png",
        skill1name: "Wordpress",
        skill2: "images/languages/css-white.png",
        skill2name: "CSS3",
        video: "images/proyectos/tobyco.mp4",
        fecha: "2024-09-15",
        destacado: false
    }
];
